# Generated by Django 6.0.2 on 2026-05-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_role_subscription_profile_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_on_leave',
            field=models.BooleanField(default=False, help_text='Designates whether this user is currently on leave.'),
        ),
    ]
