# Generated by Django 6.0.3 on 2026-05-23 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_on_leave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='assigned_supervisor',
        ),
        migrations.AddField(
            model_name='profile',
            name='assigned_supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervised_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
