# Generated by Django 6.0.3 on 2026-03-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_supervisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
