# Generated by Django 6.0.3 on 2026-03-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_task_expected_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('CP', 'Completed'), ('CN', 'Cancelled'), ('PP', 'Postponed')], default='NS', max_length=2),
        ),
    ]
