# Generated by Django 6.0.2 on 2026-05-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_note_options_objective_task_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='description',
        ),
    ]
