# Generated by Django 6.0.2 on 2026-05-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_objective_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='actual_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
