# Generated by Django 6.0.2 on 2026-05-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_objective_actual_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.note'),
        ),
    ]
