# Generated by Django 6.0.2 on 2026-08-31 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_note_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWorkplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('owner', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WorkplanActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('CP', 'Completed'), ('PP', 'Postponed')], default='PD', max_length=2)),
                ('workplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.monthlyworkplan')),
            ],
            options={
                'verbose_name_plural': 'Workplan Activities',
                'ordering': ['date'],
            },
        ),
    ]
