# Generated by Django 6.0.3 on 2026-08-31 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_monthlyworkplan_workplanactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplanactivity',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplan_activities', to='tasks.task'),
        ),
    ]
